# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

sim

In [4]:
import numpy as np
import pandas as pd

list = [1,2,3,4,5]
array_1 = np.array(
    list
)
print(array_1)

[1 2 3 4 5]

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [5]:
from dados import lista_gene_epsilon_adaptin, lista_gene_GAPDH, lista_gene_PIK3CA, lista_TcUGD, lista_gene_TcGP72

lista_multidimensional = [
    lista_gene_epsilon_adaptin,
    lista_gene_PIK3CA,
    lista_gene_GAPDH,
    lista_TcUGD,
    lista_gene_TcGP72

]

lista_multidimensional

[[15, 'ep', 2, False],
 [6, 'PI', 0, False],
 [5, 'GA', 0, False],
 [5, 'Tc', 0, False],
 [6, 'Tc', 0, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [6]:
array_dos_genes = np.array(lista_multidimensional)
array_dos_genes

array([['15', 'ep', '2', 'False'],
       ['6', 'PI', '0', 'False'],
       ['5', 'GA', '0', 'False'],
       ['5', 'Tc', '0', 'False'],
       ['6', 'Tc', '0', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [7]:
array_dos_genes[2,:]

array(['5', 'GA', '0', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [8]:
array_dos_genes[:,3]

array(['False', 'False', 'False', 'False', 'False'], dtype='<U21')

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [9]:
print(array_dos_genes[1,(1,2)])
print(array_dos_genes[3,(1,2)])

['PI' '0']
['Tc' '0']

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [17]:
from dados import gene_list_dict
gene_dataframe = pd.DataFrame(gene_list_dict)
gene_dataframe = gene_dataframe.transpose()
gene_dataframe.rename(columns={
                0: 'num_letras',
                1: 'primeiras_duas_letras',
                2: 'num_a',
                3: 'contains_hu'
            }, inplace=True)
gene_dataframe

                num_letras primeiras_duas_letras num_a contains_hu
epsilon-adaptin         15                    ep     2       False
PIK3CA                   6                    PI     0       False
GAPDH                    5                    GA     0       False
TcUGD                    5                    Tc     0       False
TcGP72                   6                    Tc     0       False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [20]:
gene_dataframe.iloc[:,[0,2]]

                num_letras num_a
epsilon-adaptin         15     2
PIK3CA                   6     0
GAPDH                    5     0
TcUGD                    5     0
TcGP72                   6     0

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [12]:
gene_dataframe.iloc[3,[0,2]]

0    5
2    0
Name: TcUGD, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [13]:
import pandas as pd
import numpy as np

dados_de_seguro_na_florida_em_2012 = pd.read_csv('data.csv')
dados_de_seguro_na_florida_em_2012.head()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1

In [22]:


dicionario = {
    "numero_de_entradas" : dados_de_seguro_na_florida_em_2012.count() ,
    "classe_das_colunas" : dados_de_seguro_na_florida_em_2012.iloc[0].apply(type),
    "numero_de_elementos_de_cada_classe" : dados_de_seguro_na_florida_em_2012.replace(0, np.nan).nunique(),
    "media_por_coluna" : dados_de_seguro_na_florida_em_2012.select_dtypes(include="number").iloc[:, [0, 3, 8]].mean(),
    "desvio_padrao_por_coluna" : dados_de_seguro_na_florida_em_2012.select_dtypes(include="number").iloc[:, [0, 3, 8]].std(),
    "média_por_coluna" : dados_de_seguro_na_florida_em_2012.iloc[:, [0, 3, 8]].quantile(0.75)
}

dicionario

{'numero_de_entradas': policyID              36634
 statecode             36634
 county                36634
 eq_site_limit         36634
 hu_site_limit         36634
 fl_site_limit         36634
 fr_site_limit         36634
 tiv_2011              36634
 tiv_2012              36634
 eq_site_deductible    36634
 hu_site_deductible    36634
 fl_site_deductible    36634
 fr_site_deductible    36634
 point_latitude        36634
 point_longitude       36634
 line                  36634
 construction          36634
 point_granularity     36634
 dtype: int64,
 'classe_das_colunas': policyID                <class 'numpy.int64'>
 statecode                       <class 'str'>
 county                          <class 'str'>
 eq_site_limit         <class 'numpy.float64'>
 hu_site_limit         <class 'numpy.float64'>
 fl_site_limit         <class 'numpy.float64'>
 fr_site_limit         <class 'numpy.float64'>
 tiv_2011              <class 'numpy.float64'>
 tiv_2012              <class 'numpy.float64'>
 eq_site_deductible    <class 'numpy.float64'>
 hu_site_deductible    <class 'numpy.float64'>
 fl_site_deductible    <class 'numpy.float64'>
 fr_site_deductible      <class 'numpy.int64'>
 point_latitude        <class 'numpy.float64'>
 point_longitude       <class 'numpy.float64'>
 line                            <class 'str'>
 construction                    <class 'str'>
 point_granularity       <class 'numpy.int64'>
 Name: 0, dtype: object,
 'numero_de_elementos_de_cada_classe': policyID              36634
 statecode                 1
 county                   67
 eq_site_limit          5960
 hu_site_limit         24530
 fl_site_limit          4580
 fr_site_limit          7535
 tiv_2011              24804
 tiv_2012              35295
 eq_site_deductible      154
 hu_site_deductible     2152
 fl_site_deductible       42
 fr_site_deductible        5
 point_latitude        17900
 point_longitude       17731
 line                      2
 construction              5
 point_granularity         5
 dtype: int64,
 'media_por_coluna': policyID              548661.937189
 fl_site_limit         664600.937028
 hu_site_deductible      7037.984547
 dtype: float64,
 'desvio_padrao_por_coluna': policyID              2.599129e+05
 fl_site_limit         1.746114e+07
 hu_site_deductible    9.582593e+04
 dtype: float64,
 'média_por_coluna': policyID         7.742520e+05
 eq_site_limit    0.000000e+00
 tiv_2012         1.128871e+06
 Name: 0.75, dtype: float64}