In [5]:
num_1 = 4
num_2 = 2
print(num_1 + num_2)

6

In [6]:
lista_1 = [1,2,3,4,5,6]
lista_1[1] += 2
lista_1

[1, 4, 3, 4, 5, 6]

In [7]:
import numpy as np  
import pandas as pd

In [8]:
array = np.array(lista_1)
print(array)
array += 2
print(array)
array *= 2
print(array)
array **= 2
print(array)

[1 4 3 4 5 6]
[3 6 5 6 7 8]
[ 6 12 10 12 14 16]
[ 36 144 100 144 196 256]

In [9]:
np.insert(arr=array, obj=-0, values= array)[::-1]

array([256, 196, 144, 100, 144,  36, 256, 196, 144, 100, 144,  36])

In [10]:
array = np.array(lista_1).reshape(-1,3)
array

array([[1, 4, 3],
       [4, 5, 6]])

In [11]:
df = pd.DataFrame(array)
df

   0  1  2
0  1  4  3
1  4  5  6

In [12]:
df += df
df

   0   1   2
0  2   8   6
1  8  10  12

In [13]:
array_ones = np.ones_like(df)
array_ones[0,0] = 100
print(array_ones)
df += array_ones
df

[[100   1   1]
 [  1   1   1]]

     0   1   2
0  102   9   7
1    9  11  13